export { default as LogoImage } from "./Frame 3.png";
export { default as HomeLeftRectangle } from "./Rectangle 6.png";
export { default as HomeRightRectangle } from "./Rectangle 5.png";
export { default as HomeBannerRectangle } from "./Rectangle 1.png";
export { default as HomeDashboardImage } from "./42_Dashboard 2.png";
export { default as GoogleImage } from "./google.png";
export { default as AmazondImage } from "./Vector.png";
export { default as SpotifyImage } from "./Vector (1).png";
export { default as CardWaveimage } from "./Group.png";
export { default as UserWithChartOne } from "./Frame 11347.png";
export { default as UserWithChartTwo } from "./Frame 11348.png";
export { default as UserWithChartThree } from "./Frame 11349.png";
export { default as ArcheryImage } from "./Archery.png";
export { default as GroupAnalytics } from "./Group 19.png";
export { default as YellowTrophy } from "./Frame 33.png";
export { default as BlueTrophy } from "./Frame 33 (1).png";
export { default as GreenTrophy } from "./Frame 33 (2).png";
export { default as ApproveYellow } from "./Approve.png";
export { default as CloseYellow } from "./Close.png";
export { default as BusinessApprove } from "./BusinessApprove.png";
export { default as PremiumApprove } from "./PremiumApprove.png";
export { default as InstagramImage } from "./Frame 58.png";
export { default as FacebookImage } from "./Frame 59.png";
export { default as YoutubeImage } from "./Frame 60.png";
export { default as FooterLogo } from "./NftiseLogo.png";
