export { default as LogoImage } from "./Frame 3.png";
export { default as HomeLeftRectangle } from "./Rectangle 6.png";
export { default as HomeRightRectangle } from "./Rectangle 5.png";
export { default as HomeBannerRectangle } from "./Rectangle 1.png";
export { default as HomeDashboardImage } from "./42_Dashboard 2.png";
export { default as GoogleImage } from "./google.png";
export { default as AmazondImage } from "./Vector.png";
export { default as SpotifyImage } from "./Vector (1).png";
export { default as CardWaveimage } from "./Group.png";
export { default as UserWithChartOne } from "./Frame 11347.png";
export { default as UserWithChartTwo } from "./Frame 11348.png";
export { default as UserWithChartThree } from "./Frame 11349.png";
export { default as ArcheryImage } from "./Archery.png";
export { default as GroupAnalytics } from "./Group 19.png";